loop create-dmg to deal with failures on x86 build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -166,17 +166,28 @@ jobs:
       - name: Create dmg MacOS
         if: matrix.os == 'macos-x86' || matrix.os == 'macos-arm64'
         run: |
+        # Adding retries in since create-dmg seems to often fail on x86
           chmod a+x "dist/MarkerMatic.app"
           brew update
           brew install create-dmg
-          create-dmg \
-          --volname "MarkerMatic Installer" \
-          --app-drop-link 600 185 \
-          --window-pos 200 120 \
-          --window-size 800 400 \
-          --hide-extension "MarkerMatic.app" \
-          "MarkerMatic Installer"-${{ matrix.target }}.dmg \
-          "dist/MarkerMatic.app"
+          max_tries=10
+          i=0
+          until create-dmg \
+            --volname "MarkerMatic Installer" \
+            --app-drop-link 600 185 \
+            --window-pos 200 120 \
+            --window-size 800 400 \
+            --hide-extension "MarkerMatic.app" \
+            "MarkerMatic Installer"-${{ matrix.target }}.dmg \
+            "dist/MarkerMatic.app"
+          do
+            if [ $i -eq $max_tries ]
+            then
+              echo 'Error: create-dmg did not succeed even after 10 tries.'
+              exit 1
+            fi
+            i=$((i+1))
+          done
       # Zip the windows applications
       - name: Create zip on Windows
         if: matrix.os == 'windows-latest'
